<map version="1.0.1">
<node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">Parameter </font></b>(<font color="#000000">ClassParameter</font>)</p></body></html></richcontent><node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">Echo </font></b>(<font color="#000000">ClassParameterEcho</font>)</p></body></html></richcontent><node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">Delay </font></b>(<font color="#000000">double</font>)</p></body></html></richcontent></node><node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">EchoAmplitudeFactor </font></b>(<font color="#000000">double</font>)</p></body></html></richcontent></node></node>
<node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">Filter </font></b>(<font color="#000000">ClassParameterFilter</font>)</p></body></html></richcontent><node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">Lowpass </font></b>(<font color="#000000">ClassParameterLowpass</font>)</p></body></html></richcontent><node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">HeigherCutOff </font></b>(<font color="#000000">double</font>)</p></body></html></richcontent></node><node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">FilterType </font></b>(<font color="#000000">char</font>)</p></body></html></richcontent></node></node>
<node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">Highpass </font></b>(<font color="#000000">ClassParameterHighpass</font>)</p></body></html></richcontent><node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">LowerCutOff </font></b>(<font color="#000000">double</font>)</p></body></html></richcontent></node><node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">FilterType </font></b>(<font color="#000000">char</font>)</p></body></html></richcontent></node></node>
<node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">Bandpass </font></b>(<font color="#000000">ClassParameterBandpass</font>)</p></body></html></richcontent><node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">LowerCutOff </font></b>(<font color="#000000">double</font>)</p></body></html></richcontent></node><node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">HeigherCutOff </font></b>(<font color="#000000">double</font>)</p></body></html></richcontent></node><node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">FilterType </font></b>(<font color="#000000">char</font>)</p></body></html></richcontent></node></node>
</node>
<node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">Amplify </font></b>(<font color="#000000">ClassParameterAmplify</font>)</p></body></html></richcontent><node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">LeftGain </font></b>(<font color="#000000">double</font>)</p></body></html></richcontent></node><node><richcontent TYPE="NODE"><html><body><p style="text-align: center"><b><font color="#3333ff">RightGain </font></b>(<font color="#000000">double</font>)</p></body></html></richcontent></node></node>
</node>
</map>
